export const soundEffects = {
    type: new Audio('soundEffects/type.mp3'),
    buttonPress: new Audio('soundEffects/buttonPress.mp3'),
    buttonPressSelect: new Audio('soundEffects/buttonPressSelect.mp3'),
    flipCard: new Audio('soundEffects/flipCard.mp3'),
    selectCard: new Audio('soundEffects/selectCard.mp3'),
    buttonPressNav: new Audio('soundEffects/buttonPressNav.mp3'),
    attack: new Audio('soundEffects/attack.mp3'),
    dmgTake: new Audio('soundEffects/dmgTake.mp3'),
    activeSkillPop: new Audio('soundEffects/activeSkillPop.mp3'),
    activeSkillCharge: new Audio('soundEffects/activeSkillCharge.mp3'),
    burn: new Audio('soundEffects/burn.mp3'),
    bleed: new Audio('soundEffects/bleed.mp3'),
    poison: new Audio('soundEffects/poison.mp3'),
    heal: new Audio('soundEffects/heal.mp3'),
    accept: new Audio('soundEffects/accept.mp3'),
    decline: new Audio('soundEffects/decline.mp3'),
    fail: new Audio('soundEffects/fail.mp3'),
    navButton: new Audio('soundEffects/navButton.mp3'),
    request: new Audio('soundEffects/request.mp3'),
    select: new Audio('soundEffects/select.mp3'),
    success: new Audio('soundEffects/success.mp3'),
}
