export const CARDS_ACTION_TYPES = {
    SET_CARDS: 'SET_CARDS',
    SET_PLAYER_BATTLE_CARDS: 'SET_PLAYER_BATTLE_CARDS',
    SET_BOSS_CARDS: 'SET_BOSS_CARDS',
    SET_OPPONENT_BATTLE_CARDS: 'SET_OPPONENT_BATTLE_CARDS',
  }